# Site settings
title: "Clianz: Tech and stuff from NZ"
#logo: logo.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: opportunities@clianz.com
description: > # this means to ignore newlines until "url:"
  Thoughts exploration on software, hardware, and all things in technology.
url: "http://www.clianz.com"
#baseurl: "/joon" # the subpath of your site, e.g. /blog/
twitter_username: jekyllrb
github_username:  jekyll

permalink: pretty
paginate: 5
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
